name: VitalRules
version: @version@
main: com.tamrielnetwork.vitalrules.VitalRules
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to see server rules.
commands:
  rules:
    description: "Main command"
    usage: "/rules"
permissions:
  vitalrules.rules:
    description: "Permission to see server rules"
    default: op